apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: text-generation-inference
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: text-generation-inference
    app.kubernetes.io/part-of: kserve
  name: text-generation-inference
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: text-generation-inference
status:
  loadBalancer: {}
